DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS categories;

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50)
  email text UNIQUE NOT NULL
  -- this is where I need help
  categories 
  transactions
  -- this is where I need help
)
CREATE TABLE categories  (
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(50) NOT NULL
);

CREATE TABLE transactions (
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
venue VARCHAR(50) NOT NULL,
amount DECIMAL(6,2) NOT NULL,
comments TEXT ,
category_id INTEGER REFERENCES categories(id)
);